### ISSUE TITLE
My spin on the theme

### ISSUE THREAD

**Issue by deybhayden** [nathanbuchar/atom-one-dark-terminal#1]
Hey, thanks for making these color schemes! Just wanted to show my version as well (based off yours)

![screen shot 2015-06-02 at 11 16 54 am](https://cloud.githubusercontent.com/assets/877908/7940845/fcb6d3fc-0918-11e5-9b7b-6e512d9cd26f.png)

[My exported theme](https://github.com/beardedprojamz/DotFiles/blob/master/OneDark.itermcolors)

**Comment by deybhayden** [comment]
They now posted a new update on the theme with all new colors... so nevermind. :frowning:

**Comment by nathanbuchar** [comment]
Yup! And the new 0.7.0 colors for One Dark have already been added to this repo. Thanks for your interest :smiley:
