### ISSUE TITLE
Any chances on a konsole version?

### ISSUE THREAD

**Issue by dansdantas** [nathanbuchar/atom-one-dark-terminal#10]
I really liked but i'm using konsole now. Can we have a version for it?

**Comment by dansdantas** [comment]
I was answered on reddit that you convert your terminal version on konsole just using https://terminal.sexy/.

Link for discussion: https://www.reddit.com/r/kde/comments/53mski/atoms_one_dark_coloscheme_for_konsole/

**Comment by nathanbuchar** [comment]
Oh sorry, forgot to look into this! GitHub really needs a "remind me later" button, haha. Great, I'm glad you found a solution, I'll check out the link and see if I can add a Konsole version within the repo
