### ISSUE TITLE
Can't type caracter `~`

### ISSUE THREAD

**Issue by proov** [nathanbuchar/atom-one-dark-terminal#11]
Hello !

When i try to type the character `~` with `alt+n`. The terminal insert a semicolon `;` 

I switched back to the Mac default white terminal theme, the tilde character works as expected with `alt+n`

Do you have an idea why ?

**Comment by nathanbuchar** [comment]
Look into the advanced and keyboard settings of the theme and compare them to the default profile. I may have accidentally changed something in there for some other purpose and it somehow got carried through when I exported this theme

**Comment by proov** [comment]
I found it ! You were right ! The 1st checkbox was checked ! :)

![](http://reho.st/self/6b6745ce3a0d6562ee5c7eca4c22ba115655aacb.png)

**Comment by nathanbuchar** [comment]
Ah, yes I like using the option key :)
