### ISSUE TITLE
How to install under ubuntu 16.04?

### ISSUE THREAD

**Issue by agostini01** [nathanbuchar/atom-one-dark-terminal#12]
I apologize for my lack of knowledge, but could  explain how to install on ubuntu 16.04?

Thanks in advance,
Nico

**Comment by nathanbuchar** [comment]
Sorry, I'm not familiar with Linux :\\. Try Googling "how to install terminal theme ubuntu"

**Comment by nathanbuchar** [comment]
You can also add the colors manually in your Terminal profile. The color used for this theme can be found [here](https://github.com/nathanbuchar/atom-one-dark-terminal/blob/master/COLORS).

**Comment by agostini01** [comment]
Hello! This last message solved my request.
I matched bash base 16 scheme to the colors provided. :)
Thank you!
