### ISSUE TITLE
Cmder

### ISSUE THREAD

**Issue by victorwpbastos** [nathanbuchar/atom-one-dark-terminal#13]
Please create a Cmder variant. A lot of Windows users would appreciate.

**Comment by nathanbuchar** [comment]
For your convenience, the colors used in the theme can be found [here](https://github.com/nathanbuchar/atom-one-dark-terminal/blob/master/COLORS). If you make a new cmder theme using those colors and PR it in, I'll accept it :)

**Comment by victorwpbastos** [comment]
I ended using this: https://github.com/joonro/ConEmu-Color-Themes/blob/master/one-dark.xml. Thanks, BTW.

**Comment by obrotowy** [comment]
Error 404 :(

**Comment by nathanbuchar** [comment]
@SynneK1337 [Found it for you](https://github.com/joonro/ConEmu-Color-Themes/blob/master/themes/one-dark.xml)
