### ISSUE TITLE
Unverified release?!

### ISSUE THREAD

**Issue by pothi** [nathanbuchar/atom-one-dark-terminal#14]
Hello,

I wonder, if it is safe to download the latest version. I noticed a warning message on the releases page for the last few releases (the earlier / initial releases were okay). Please see the screenshot below to understand what I am talking about...

![screen shot 2017-03-15 at 8 18 45](https://cloud.githubusercontent.com/assets/1254302/23954282/dc301836-09bc-11e7-99fe-8544ae9c296b.jpg)

Thank you.

**Comment by nathanbuchar** [comment]
All is well! Must have signed it with my work GPG key not my personal key.

**Comment by pothi** [comment]
Thanks for clarifying.
