### ISSUE TITLE
Colors in mc

### ISSUE THREAD

**Issue by chimit** [nathanbuchar/atom-one-dark-terminal#17]
Is there any way to make mc colors better for this theme?

<img width="714" alt="2018-02-24 15 09 51" src="https://user-images.githubusercontent.com/839349/36626832-d619a00c-1974-11e8-90ea-e04234d0d847.png">

**Comment by nathanbuchar** [comment]
Golly! I'm not familiar with mc. Is it an alternative to Terminal?

**Comment by chimit** [comment]
Hi!
It's a Midnight Commander. You can install it as `sudo apt-get install mc` in Ubuntu, for example.

**Comment by nathanbuchar** [comment]
Ah, well you can find the list of colors used for this theme [here](https://github.com/nathanbuchar/atom-one-dark-terminal/blob/master/COLORS). If you make an MC-compatible theme, please feel free to PR :)
