### ISSUE TITLE
Enabling Colors

### ISSUE THREAD

**Issue by PKeves** [nathanbuchar/atom-one-dark-terminal#18]
I can't seem to be able to enable the colors on the terminal despite following the instructions

**Comment by ADO** [comment]
@PKeves in addition to running the `~/.bashrc` change, also make sure you download the Terminal config files for [One Dark](https://github.com/nathanbuchar/atom-one-dark-terminal/raw/master/scheme/terminal/One%20Dark.terminal) (my favourite) and/or [One Light](https://github.com/nathanbuchar/atom-one-dark-terminal/raw/master/scheme/terminal/One%20Light.terminal) and import them via Terminal preferences via the settings icon dropdown at the bottom. And set whichever choice to default.
