### ISSUE TITLE
No v1.0.1 for iTerm

### ISSUE THREAD

**Issue by cardinallijr** [nathanbuchar/atom-one-dark-terminal#2]
Hi Nathan,

First of all thanks for working on that, I really like One dark theme on Atom and I wanted the same look n' feel for iTerm. I wasn't able to find the latest version (1.0.1) for iTerm but I'm using 1.0.0 by now. Just wanted to report that.

Thanks again.
## 

Alberto

**Comment by nathanbuchar** [comment]
Ah! My bad, I seem to have put it in the wrong folder. I just pushed a fix for this :-). You may also download the files directly by visiting the "releases" tab https://github.com/nathanbuchar/one-dark-terminal/releases/tag/v1.0.1
