### ISSUE TITLE
Explain how to add the theme on terminal in the README

### ISSUE THREAD

**Issue by noook** [nathanbuchar/atom-one-dark-terminal#22]
There is currently no information on how to add the theme. I tried in preferences but I'm not sure it is that.

**Comment by setanarut** [comment]
> There is currently no information on how to add the theme. I tried in preferences but I'm not sure it is that. @neilrichter 

https://github.com/lysyi3m/macos-terminal-themes#installation-instructions

**Comment by sergeevabc** [comment]
Could you be so kind to provide HEX colour values of this theme?

**Comment by setanarut** [comment]
> Could you be so kind to provide HEX colour values of this theme?

https://github.com/nathanbuchar/atom-one-dark-terminal/blob/master/COLORS
