### ISSUE TITLE
Update Readme for Catalina

### ISSUE THREAD

**Issue by TechRemarker** [nathanbuchar/atom-one-dark-terminal#26]
The latest macOS Catalina now uses Zsh by default so the Readme should be updated with a note on the command required for Catalina.

`echo -e '\n# Add colors to Terminal\nexport CLICOLOR=1\nexport LSCOLORS=GxFxCxDxBxegedabagaced' >> ~/.zhrc`

**Comment by ottoman91** [comment]
hi, i ran this command on the CLI but i still cant see the colors. Is there another step that i am missing out on? i am running catalina version 10.15.5 thanks!

**Comment by dmofot** [comment]
@ottoman91 the command just has a misspelling in the filename.  It should be:
`echo -e '\n# Add colors to Terminal\nexport CLICOLOR=1\nexport LSCOLORS=GxFxCxDxBxegedabagaced' >> ~/.zshrc`

**Comment by nathanbuchar** [comment]
Anyone up for doing a quick PR for this?
