### ISSUE TITLE
useOptionAsMetaKey

### ISSUE THREAD

**Issue by setanarut** [nathanbuchar/atom-one-dark-terminal#29]
`useOptionAsMetaKey = true` With this non default setting, when the @ sign is written, the terminal suddenly close.

<img width="184" alt="cap 1" src="https://user-images.githubusercontent.com/36481442/89807309-1a5ed080-db41-11ea-8764-74861bde6913.png">
<img width="245" alt="cap" src="https://user-images.githubusercontent.com/36481442/89807315-1d59c100-db41-11ea-8e29-b149e144bfc6.png">

Option+Q = @
Command+Q = Quit

it should be `useOptionAsMetaKey = false`

**Comment by nathanbuchar** [comment]
This is a setting I have on my own personal terminal that must have carried over when I exported my profile for this theme. You're right in that it is not set by default. Feel free to submit a PR with this change :)
