### ISSUE TITLE
Include instructions for changing syntax colors

### ISSUE THREAD

**Issue by k4j8** [nathanbuchar/atom-one-dark-terminal#3]
Since Terminal profiles only set the available colors for Terminal to choose from, could you include whatever `~/.profile` and other changes you made to achieve the screenshots in the README? For example, your name is colored at the beginning of each line and the `ls` output has syntax highlighting.

Thanks for the themes! I'm using Atom's shortcuts and themes whenever possible on my computer.

**Comment by nathanbuchar** [comment]
Certainly! I'm indisposed for this week and part into next, but for now I can tell you that I'm using [.oh-my-zsh](https://github.com/ronert/.oh-my-zsh) with the built-in `gallifrey` theme.

**Comment by k4j8** [comment]
Thanks! I tried it out and it looks great. Using the theme without zsh is kind of bland. This is much better.
