### ISSUE TITLE
Colors? 

### ISSUE THREAD

**Issue by discentem** [nathanbuchar/atom-one-dark-terminal#4]
How do I get the text color to work in terminal?

**Comment by nathanbuchar** [comment]
[This should help](http://osxdaily.com/2013/02/05/improve-terminal-appearance-mac-os-x/). Let me know if you run into any issues :-)

The gist of it is to append

```
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
```

to your `~/.bash_profile`

**Comment by discentem** [comment]
Thanks Nathan. Worked like a charm.

**Comment by nathanbuchar** [comment]
Great!
