### ISSUE TITLE
Having Trouble With Colors

### ISSUE THREAD

**Issue by sledrabbit** [nathanbuchar/atom-one-dark-terminal#6]
When I import the *.terminal file into terminal preferences, all I see in the shell window is a light blue font over a gray background. 

Do you know why none of the colors are working?

**Comment by kfalkiewicz** [comment]
Hi,
1. Can you add screenshot?
2. Did you installed z-term?
3. Did you activated it in settings of terminal?

**Comment by sledrabbit** [comment]
Using regular Terminal that comes with Mac. I did try the *.itermcolors profile in iTerm 2 with no luck though. 
![screen shot 2016-07-22 at 2 44 55 pm](https://cloud.githubusercontent.com/assets/20589051/17072152/067dff60-501b-11e6-9d1f-d49be26b62f8.png)

**Comment by nathanbuchar** [comment]
Hey, thanks for trying it out!

Take a look at #4. That should do the trick :)

**Comment by sledrabbit** [comment]
Interesting that we need to create a .bash_profile to have ls colors etc. Should have colors by default in OS X. 

Anyway, thanks Nathan that solved it!
