### ISSUE TITLE
Theme colors not changing text

### ISSUE THREAD

**Issue by julesmoretti** [nathanbuchar/atom-one-dark-terminal#8]
Hi @nathanbuchar:

I have imported your theme as is into my terminal and made sure it was the default theme for it. Though having done so and that the color in the preferences did load, the terminal window though being the right dark hue only shoes grey text #ABB2BF.

Does this theme require a specific shell or extra configs or fonts?

Thank you for your help.

**Comment by nathanbuchar** [comment]
See #4 :)

I should really add that to the README

**Comment by julesmoretti** [comment]
Thank you, and yes please 👍
