### ISSUE TITLE
Blackness

### ISSUE THREAD

**Issue by amk221** [nathanbuchar/atom-one-dark-terminal#9]
I run `npm install` frequently, and it looks like this:

<img src="https://cloud.githubusercontent.com/assets/382061/17565915/3ebfcde8-5f31-11e6-8c82-b617bb48590c.png" width="220">

However, I would expect it to look like this:

<img src="https://cloud.githubusercontent.com/assets/382061/17565906/34079f7a-5f31-11e6-8b6f-7777778c8271.png" width="220">

**Comment by nathanbuchar** [comment]
Thanks for trying it out :)

I believe the background color is applied on npm's side. I've looked through their code a little bit to see if I can find exactly where it's coming from but unfortunately that's no easy task.. However, here is the output in a Terminal window using the default "Basic" theme:

![image](https://cloud.githubusercontent.com/assets/1815367/17566832/c9dec270-5ef1-11e6-81c1-36a8663b0cc7.png)

As you can see the background color for each module is still black, so I don't think it's related to the one-dark-terminal theme but rather npm itself, as that is how they've chosen to display tree views.

**Comment by amk221** [comment]
Ah thanks, nice spot.

**Comment by amk221** [comment]
Apologies if this a daft question, but why is black even a part of the One Dark theme?
If I change Black to the Background colour provided by One Dark theme, it looks fine as per my original screenshot.

<img width="286" alt="screen shot 2016-08-10 at 21 43 20" src="https://cloud.githubusercontent.com/assets/382061/17570299/bc66b4ca-5f43-11e6-8301-0442d0e4a52e.png">

**Comment by nathanbuchar** [comment]
That's a good point.. I'd be a bit hesitant to not have "Black" be "#000000", but if it won't cause any conflicts elsewhere I see no reason why not. Do you know where else this black color may be used?

**Comment by amk221** [comment]
I'm afraid I don't know enough about terminal colours... but Solarized Dark doesn't have Black

<img width="209" alt="screen shot 2016-08-10 at 21 57 41" src="https://cloud.githubusercontent.com/assets/382061/17570720/8012f680-5f45-11e6-9d7f-64b2f683325c.png">

**Comment by nathanbuchar** [comment]
Good enough for me, I'll post an update tonight. Thanks for the tip!

**Comment by nathanbuchar** [comment]
This won't be solvable for the one-light theme, however. I'm not going to use `#FFFFFF` as "Black" haha, but for one-dark it shouldn't be an issue
